spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task_management_sys?useSSL=false&serverTimezone=UTC
    username: root
    password: 5723156
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

jwt:
  secret: A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6Q7r8
  expiration: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none